### PR TITLE
update to fastify v3

### PR DESCRIPTION
**Pull request by ferco0**

### CODE REVIEW

**Comment by PavelPolyakov** [comment]
oh that nice, looks neat. Can you, please, update the version in `package.json` as well and check if plugin continues to work? If it doesn't, I'll do fixes.

**Comment by ferco0** [comment]
Sorry for not doing this before, I updated the dependencies and ran the tests. The main problem was in typescript dev environment, looks good now.

**Comment by PavelPolyakov** [comment]
Thanks for your contribution!

**Comment by PavelPolyakov** [comment]
published

**Pull request merged**
