### PR TITLE
Switched to ESM and integrated into @fastify/* namespace

### PR DESCRIPTION
**Pull request by radaalinmihai**

### CODE REVIEW

**Comment by PavelPolyakov** [comment]
Thank you for your work, looks good to me ✅

**Comment by PavloPoliakov** [comment]
@radaalinmihai thanks for your effort, I've released [fastify-blipp@4](https://www.npmjs.com/package/fastify-blipp). I had to switch back from `@fastify/` to the original naming, since this plugin is not considered as a [core one](https://www.fastify.io/ecosystem/), so I can not publish to that namespace.

I also updated all the dependencies.

**Comment by radaalinmihai** [comment]
> @radaalinmihai thanks for your effort, I've released [fastify-blipp@4](https://www.npmjs.com/package/fastify-blipp). I had to switch back from `@fastify/` to the original naming, since this plugin is not considered as a [core one](https://www.fastify.io/ecosystem/), so I can not publish to that namespace.
> 
> I also updated all the dependencies.

No problem, glad I could help!

**Comment by PavloPoliakov** [comment]
Hi @radaalinmihai ,

May I ask if you use this module together with the TypeScript app somewhere?
I want to, but see that `ESM` module is an issue. 

It fails with:
```
/%REDACTED%/1to100/api/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /%REDACTED%/1to100/api/node_modules/fastify-blipp/src/index.js from /%REDACTED%/1to100/api/src/fastify.ts not supported.
```
and I don't see a way to overcome it. I consider to revert ESM module and release the version 5.

**Pull request merged**
